<css src="//views/databases/css/databases.scss"/>
<section class="databases">
    <nav class="db-left">
        <ul class="uk-navbar-nav uk-thumbnav-vertical">
            <li class="uk-text-center">
                <a
                    class="active"
                    href="#Databases/connections"
                    uk-tooltip="title: Select Connection"
                    core.event.click.load="Databases/connections">
                    <i class="fa fa-exchange fa-2x"/>
                </a>
            </li>
        </ul>
    </nav>
    <div class="db-right">
        <header class="uk-flex uk-flex-around">
            <span>SELECT CONNECTION </span>
            <a
                href="#Database/editConnections"
                core.event.click.load="Databases/editConnections">
                <i
                    class="uk-icon-button"
                    uk-icon="icon: file-edit"
                    uk-tooltip="title: Edit Connections"/>
            </a>
        </header>
        <ul class="uk-list" foreach="connections as connection">
            <li>
                <i class="fa fa-exchange"/>
                <span> ${connection.alias}</span>
            </li>
        </ul>
    </div>
</section>