<div class="uk-margin">
    <label class="uk-form-label" for="@{id}">@{label}</label>
    <div class="uk-form-controls uk-inline" style="width:100%">
        <textarea
            class="uk-textarea @{class}@{size}"
            id="@{id}"
            name="@{name}"
            rows="@{rows}"
            placeholder="@{placeholder}"
            required="@{required}"
            disabled="@{disabled}">
            @{value}
        </textarea>
    </div>
</div>
