<div></div>
<div class="js-upload uk-placeholder uk-text-center @{class}" id="@{id}" style="@{style}">
    <span uk-icon="icon: cloud-upload"></span>
    <span class="uk-text-middle"> Drop @{type} here</span>
    <div uk-form-custom="true">
        <input type="file"/>
        <span class="uk-link">selecting one</span>
    </div>
</div>
<progress id="js-progressbar" class="uk-progress" value="0" max="100" hidden="hidden"></progress>
<input name="@{name}" value="@{value}" type="hidden" id="_upload_file_name"/>
<input name="_upload_file_type" value="@{type}" type="hidden" id="_upload_file_type"/>

<div class="uk-margin" id="_upload_file_preview" style="display:none">
    <if value="@{type}" equalto="image">
        <img id="_upload_file_preview_src" src="${env.project.upload.url}@{type}s/@{folder}/@{value}" style="width: 100%"/>
    </if>

    <if value="@{type}" notequalto="image">
        <a id="_upload_file_preview_href" target="_blank" href="${env.project.upload.url}@{type}s/@{folder}/@{value}">@{value}</a>
    </if>
</div>

<script>
    <if notempty="@{value}">
        $("#_upload_file_preview").show();
    </if>

    var bar = document.getElementById('js-progressbar');
    UIkit.upload('.js-upload', {
        url: '@{url}/@{type}/@{folder}',
        multiple: false,
        beforeSend: function () {
            /* console.log('beforeSend', arguments); */
        },
        beforeAll: function () {
            /* console.log('beforeAll', arguments); */
        },
        load: function () {
            /* console.log('load', arguments); */
        },
        error: function () {
            /* console.log('error', arguments); */
        },
        complete: function () {
            /*  console.log('complete', arguments); */
        },
        loadStart: function (e) {
            /*  console.log('loadStart', arguments); */

            bar.removeAttribute('hidden');
            bar.max = e.total;
            bar.value = e.loaded;
        },
        progress: function (e) {
            /* console.log('progress', arguments); */

            bar.max = e.total;
            bar.value = e.loaded;
        },
        loadEnd: function (e) {
            /*  console.log('loadEnd', arguments); */

            bar.max = e.total;
            bar.value = e.loaded;
        },
        completeAll: function () {
            ajaxSuccessEvents($.parseJSON(arguments[0].response));

            setTimeout(function () {
                bar.setAttribute('hidden', 'hidden');
            }, 1000);
        }
    });
</script>