<!-- Load NAV Area JS -->
<lazyload
    src="views/partials/nav/js/nav.js"
    instantiate="nav"
    extend="console"
    callback="core.console.nav.init"
    context="window"/>

<header class="uk-box-shadow-medium uk-box-shadow-hover-large">
    <aside
        id="cc.header.left"
        class="left padding-10 padding-top-15">
        <import src="views/partials/nav/header/aside/left/index.phtml"/>
    </aside>
    <nav
        id="cc.header.top"
        class="top">
        <aside
            id="cc.header.top.left"
            class="left">
            ${nav.header.file}
        </aside>
        <main id="cc.header.top.main">
            <import src="views/partials/nav/header/top/main/breadcrumbs.phtml"/>
        </main>
        <aside
            id="cc.header.top.right"
            class="right"/>
    </nav>
    <nav class="bottom">
        <aside class="left">

        </aside>
        <main>

        </main>
        <aside class="right">
            <!-- Show ws-right -->
            <a
                id="show-right-ws"
                style="display: none; width: 20px; height: 20px; font-size: 13px; background-color: #d5caca; color: #212121; margin-top: 5px; margin-right: 8px;"
                uk-tooltip="title: Show right column"
                href="#show-ws-column"
                class="uk-icon-button">
                <i class="fa fa-columns"/>
            </a>

            <!-- Hide ws-right -->
            <a
                id="hide-right-ws"
                style="width: 20px; height: 20px; font-size: 13px; background-color: #d5caca; color: #212121; margin-top: 5px; margin-right: 8px;"
                uk-tooltip="title: Hide right column"
                href="#hide-ws-column"
                class="uk-icon-button">
                <span class="fa-stack fa-lg">
                    <i class="fa fa-columns fa-stack-1x"></i>
                    <i class="fa fa-ban fa-stack-1x text-danger"></i>
                </span>
            </a>
        </aside>
    </nav>
    <aside class="right">
        <import src="views/partials/nav/header/aside/right/index.phtml"/>
    </aside>
</header>
<main>
    <aside class="left">
        <div class="top">
            <import src="views/partials/nav/main/aside/left/top/index.phtml"/>
        </div>
        <div class="bottom">
            <import src="views/partials/nav/main/aside/left/bottom/index.phtml"/>
        </div>
    </aside>
    <nav class="left">

    </nav>
    <main>
        <import src="views/workspace/index.phtml"/>
    </main>

    <nav class="right">

    </nav>
    <aside class="right">
        <import src="views/partials/nav/main/aside/right/index.phtml"/>
    </aside>
</main>
<footer>
    <span>Copyright &amp;copy; </span>
    <date format="Y">${CURRENT_YEAR}</date>
    <span> ${app.website.author.company}</span>
</footer>
