<ul class="uk-subnav uk-flex uk-flex-center uk-child-width-1-6">
    <li>
        <a
            href="#"
            class="uk-icon-link"
            uk-tooltip="title: Home"
            data-uk-icon="icon: home"></a>
    </li>
    <li>
        <a
            href="#"
            class="uk-icon-link"
            uk-tooltip="title: Settings"
            data-uk-icon="icon: settings"></a>
    </li>
    <li>
        <a
            href="#"
            class="uk-icon-link"
            uk-tooltip="title: Social"
            data-uk-icon="icon: social"></a>
    </li>
    <li>
        <a
            href="#"
            class="uk-icon-link"
            uk-tooltip="title: Comment"
            data-uk-icon="icon: comment"></a>
    </li>
    <li>
        <a
            href="#"
            class="uk-icon-link"
            uk-tooltip="title: Sign Out"
            data-uk-icon="icon: sign-out"></a>
    </li>
</ul>
