<!-- Load DEV Area CSS -->
<css src="//assets/css/dev.scss"/>

<!-- Load DEV Area JS -->
<lazyload
    src="views/console/js/dev.js"
    instantiate="dev"
    extend="console"
    callback="core.console.dev.init"
    context="window"/>

<!-- Thin Left Nav Bar -->
<nav
    class="uk-navbar-container"
    id="main-left-nav"
    uk-navbar="uk-navbar"
    import="views/partials/nav/main-left-nav.phtml"/>

<div id="main-container" class="uk-flex uk-flex-left left-sub-nav-open">
    <!-- Left Sub-Nav (One Breadcrumbs above) -->
    <div
        class="uk-navbar-container nice-scroll"
        id="main-sub-left-nav-container">
        <!-- Load the dev projects nav into container -->
        <nav
            id="main-sub-left-nav"
            uk-navbar="uk-navbar">

        </nav>
    </div>

    <!-- Main Open Area MAIN (IDE) Area -->
    <main id="content-main" class="uk-flex-1">
        <div
            id="resize-drag-elem"
            draggable="true"
            class="uk-light uk-margin-remove uk-background-secondary draggable resize-drag open">
            <div id="info-panel-icon-nav">
                <ul class="uk-iconnav">
                    <li>
                        <a
                            class="icon-nav-action"
                            action="loadConsole"
                            href="#inspect/console"
                            uk-tooltip="title: Console"
                            uk-icon="icon: move">
                            <span class="uk-hidden"> Console</span>
                        </a>
                    </li>
                    <li>
                        <a
                            class="icon-nav-action"
                            action="loadAcidDom"
                            href="#inspect/elements"
                            uk-tooltip="title: Elements"
                            uk-icon="icon: album">
                            <span class="uk-hidden"> Elements</span>
                        </a>
                    </li>
                    <li>
                        <span id="info-panel-icon-nav-heading"> Console</span>
                    </li>
                    <li>
                        <a
                            class="icon-nav-action"
                            action="loadNetwork"
                            href="#inspect/network"
                            uk-tooltip="title: Network"
                            uk-icon="icon: world">
                            <span class="uk-hidden"> Network/Sources</span>
                        </a>
                    </li>
                    <li>
                        <a
                            class="icon-nav-action"
                            action="loadData"
                            href="#inspect/data"
                            uk-tooltip="title: JS Data / Local Storage"
                            uk-icon="icon: database">
                            <span class="uk-hidden"> Data</span>
                        </a>
                    </li>
                </ul>
            </div>
            <div id="dev-info-block">
                <div
                    id="dev-info-block-console"
                    class="dev-info-inner-block">

                </div>
                <div
                    id="dev-info-block-elements"
                    class="dev-info-inner-block">

                </div>
                <div
                    id="dev-info-block-sources"
                    class="dev-info-inner-block">

                </div>
                <div
                    id="dev-info-block-network"
                    class="dev-info-inner-block">

                </div>
                <div
                    id="dev-info-block-data"
                    class="dev-info-inner-block">

                </div>
            </div>
        </div>
    </main>
</div>
<div id="bottom-nav">
    Bottom menu
</div>
