<section class="cc-console-settings">
    <!-- Container Tab -->
    <div class="cc-ws-tab cc-ws-tab-top active">
        <i uk-icon="icon: home"/>
        <span> Welcome</span>
        <i class="cc-ws-tab-close" uk-icon="icon: close"/>
    </div>

    <!-- CORE Wiki Navigation -->
    <nav>
        <import src="views/wiki/nav.phtml"/>
    </nav>

    <!-- Welcome Page -->
    <main>
        <import src="views/console/home/intro.phtml"/>
    </main>
</section>

