<lazyload
    url="${env.project.views.url}console/css/"
    path="${env.project.views.path}console/css/"
    file="settings.scss"/>
<lazyload
    src="views/console/js/settings.js"
    instantiate="settings"
    extend="console"
    callback="core.console.settings.init"
    context="window"/>

<app.ws.top.tab
    icon="settings"
    title="Settings"
    active="yes"
    target="#cc-workspace .ws-right"/>
<section id="cc-console-settings">
    <nav>
        <import src="views/console/settings/nav.phtml"/>
    </nav>
    <main>
        <import src="views/console/settings/core.phtml"/>
    </main>
</section>
