<div class="ws-left-credit" >
    <!-- Welcome Message -->
    <div class="core-heading">
        <small>FGX</small>
        <span>Heepp</span>
    </div>

    <!-- Code Name and Barcode -->
    <span class="core-sub-heading">
        Heepp
    </span>
    <div>Hyper eXtensible Element PreProcessor</div>
</div>
<div class="welcome-statement">
    <h4>Some usefull info</h4>
    <ul>
        <li>
            <small class="font-fgx">FGX</small>
            <b>Heepp</b>
            <span> is developed and maintained by </span>
            <a href="http://www.fgx.co.za" target="_blank">FGX Studios</a>
        </li>
        <li>
            <span> Check out the </span>
            <a core.event.click.load="Wiki/index"
               href="#wiki/newFeatures">new features</a>
        </li>
        <li>
            <span>Download the printable </span>
            <a core.event.click.load="Wiki/index"
               href="#wiki/cheatsheet"> cheatsheet</a>
        </li>
        <li>
            <span>View the full </span>
            <a core.event.click.load="Wiki/index"
               href="#wiki/index">online documentation </a>
            <span>with code examples</span>
        </li>
    </ul>
</div>
