<div
    class="nav-main-aside left uk-navbar-nav uk-thumbnav-vertical">
    <ul class="uk-navbar-nav uk-thumbnav-vertical">
        <li class="left-menu-item uk-text-center">
            <a
                class="left-menu-a"
                href="#Projects"
                uk-icon="icon: album"
                uk-tooltip="title: Projects"
                core.event.click.load="Project/index">
            </a>
        </li>
        <li class="left-menu-item uk-text-center">
            <a
                class="left-menu-a"
                href="#Admin/nav"
                uk-icon="icon: settings"
                uk-tooltip="title: Admin / Settings"
                core.event.click.load="Console.Settings/index">
            </a>
        </li>
        <li class="left-menu-item uk-text-center">
            <a
                class="left-menu-a"
                href="#Wiki"
                uk-icon="icon: question"
                uk-tooltip="title: Wiki"
                core.event.click.load="Wiki/index">
            </a>
        </li>
    </ul>
</div>
