<lib
    library="helper"
    section="jquery-3,lazyload"/>

<lib
    library="base"
    section="core,phpjs"/>

<lib
    library="ui"
    section="uikit"/>

<lib
    library="ui-icon"
    section="fontAwesome,devicons"/>

<lib
    library="ui-scroll"
    section="nicescroll-4"/>

<!-- selectorGadget is stopping JQuery from loading
<lib
    library="ui-plugin"
    section="interact,selectorGadget,acidDom"/>
-->
<lib
    library="ui-plugin"
    section="interact"/>

<lib
    library="ui-animation"
    section="gsa-tween,gsa-drag"/>

<lib
    library="ui-alert"
    section="toastedjs"/>
