<div class="btn-group pull-right" role="group" style="margin-top: -35px; margin-right: -10px">
    <if value="${session.messageReadStatus}" equalto="1">
        <button
            type="button"
            class="btn btn-default btn-sm"
            style="border-radius: 0"
            core.event.click.load="Dashboard/index">
            Unread
        </button>
        <button
            type="button"
            class="btn btn-sm btn-dashboard active"
            style="border-radius: 0"
            core.event.click.load="Dashboard/index/1">
            Archive
        </button>
    </if>
    <if value="${session.messageReadStatus}" notequalto="1">
        <button
            type="button"
            class="btn btn-sm btn-dashboard active"
            style="border-radius: 0"
            core.event.click.load="Dashboard/index">
            Unread
        </button>
        <button
            type="button"
            class="btn btn-default btn-sm"
            style="border-radius: 0"
            core.event.click.load="Dashboard/index/1">
            Archive
        </button>
    </if>
</div>
<div class="news" foreach="messages as message">
    <row id="message_${message.id}">
        <column size="2">
            <div>
                <date format="d F">${message.created_at}</date>
            </div>
            <div>
                <date format="H:i">${message.created_at}</date>
            </div>
        </column>
        <column size="10" style="position:relative; margin-top: 0" class="message">
            <b>${message.title}</b>
            <br/>
            <span>${message.message}</span>
            <if empty="${message.hideButton}">
                <button
                    class="btn btn-xs btn-dashboard dismissButton tip"
                    rel="${message.id}"
                    style="position: absolute; top: 0; right: 0">
                    <i class="fa fa-times"
                       style="display: block;  width: 100%; height: 100%; line-height: 18px"
                       title="Mark as read"
                       data-toggle="tooltip"
                       data-placement="right"></i>
                </button>
            </if>
            <if empty="${message.hideButton}">
                <button
                    class="btn btn-xs btn-dashboard replyButton tip"
                    rel="${message.id}"
                    style="position: absolute; top: 0; right: 22px; width: 80px">
                    <i class="fa fa-reply"
                       style="display: block;  width: 100%; height: 100%; line-height: 18px"
                       title="Reply"
                       data-toggle="tooltip"
                       data-placement="right"><span> Reply</span></i>
                </button>
            </if>
        </column>
        <if notempty="${message.replies}">
            <div class="clearfix"></div>
            <div class="replies-container">
                <repeat foreach="message.replies as reply">
                    <row style="margin-bottom: 0" id="message_${reply.id}">
                        <column size="2">
                            <div>
                                <date format="d F">${reply.created_at}</date>
                            </div>
                            <div>
                                <date format="H:i">${reply.created_at}</date>
                            </div>
                        </column>
                        <column size="10" style="position:relative; margin-top: 0" class="message">
                            <b>${reply.title}</b>
                            <br/>
                            <span>${reply.message}</span>
                            <!--
                            <if empty="${reply.hideButton}">
                                <button
                                    class="btn btn-xs btn-dashboard dismissButton tip"
                                    rel="${reply.id}"
                                    style="position: absolute; top: 0; right: 0">
                                    <i class="fa fa-times"
                                       style="display: block;  width: 100%; height: 100%; line-height: 18px"
                                       title="Mark as read"
                                       data-toggle="tooltip"
                                       data-placement="right"></i>
                                </button>
                            </if>

                            <if empty="${reply.hideButton}">
                                <button
                                    class="btn btn-xs btn-dashboard replyButton tip"
                                    rel="${message.id}"
                                    style="position: absolute; top: 0; right: 22px; width: 80px">
                                    <i class="fa fa-reply"
                                       style="display: block;  width: 100%; height: 100%; line-height: 18px"
                                       title="Reply"
                                       data-toggle="tooltip"
                                       data-placement="right"><span> Reply</span></i>
                                </button>
                            </if>
                            -->
                        </column>
                    </row>
                </repeat>
            </div>
        </if>
    </row>
</div>
<row id="messageSpacer" style="height:${spacerHeight}px"/>

<div
    class="modal fade"
    id="replyModal"
    tabindex="-1"
    role="dialog"
    aria-labelledby="replyModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&amp;times;</span>
                </button>
                <h4 class="modal-title" id="replyModalLabel">Reply on message</h4>
            </div>
            <div class="modal-body">
                <core.form
                    id="message-form"
                    action="Message/sendReply"
                    method="post">
                    <input type="hidden" name="message_id" id="message_id"/>
                    <div class="form-group">
                        <label for="recipient-name" class="control-label">Recipient:</label>
                        <input type="text" class="form-control" value="Mall Management" readonly="readonly" id="recipient-name"/>
                    </div>
                    <div class="form-group">
                        <label for="message-title" class="control-label">Message Subject:</label>
                        <input type="text" class="form-control" id="message-title" required="required" name="title"/>
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="control-label">Message:</label>
                        <textarea rows="5" class="form-control" name="message" id="message-text" required="required"></textarea>
                    </div>
                    <button style="display: none" id="message-submit-button" type="submit">Submit</button>
                </core.form>
            </div>
            <div class="modal-footer">
                <button type="button" id="modal-close-button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary btn-dashboard" id="send-message-button">Send message</button>
            </div>
        </div>
    </div>
</div>


<script>
    $('.dismissButton').click(function() {
        const messageId = $(this).attr('rel');
        $.ajax({
            url : 'Message/dismissMessage/'+messageId
        }).done(function() {
            $('#message_'+messageId).fadeOut('slow',function() {
                let spacer = $('#messageSpacer');
                spacer.height(spacer.height()+110);
            });
        });
    });

    $('.replyButton').click(function() {
        let messageId = $(this).attr('rel');
        $('#message_id').val(messageId);
        $('#replyModal').modal();
        /* $.ajax({
         //     url : 'Message/replyMessage/'+messageId
         }); */
    });

    $(()=>{
        $('[data-toggle="tooltip"]').tooltip();
    });

    $(()=>{
        $('#send-message-button').click(()=>{
            $('#message-submit-button').click();
        });
    });
</script>
