<div class="main-nav-left">
    <ul class="uk-nav-default uk-nav-parent-icon uk-padding-remove uk-nav">
        <li class="uk-nav-header uk-padding-remove">
            <a
                class="main-button"
                href="#"
                core.event.click.load="HeEPP/index">
                <span class="uk-margin-small-right" uk-icon="icon: nut"/>
                <span> CORE</span>
            </a>
        </li>
        <li class="uk-nav-divider"/>
        <li class="uk-nav-header margin-top-0">HeEPP Config</li>
        <li class="uk-nav-divider"/>
        <li class="uk-parent uk-open">
            <a href="#">
                <span
                    class="uk-margin-small-right"
                    uk-icon="icon: settings"/>
                <span> Environment</span>
            </a>
            <ul class="uk-nav-sub">
                <li>
                    <a
                        href="#Products/Products"
                        core.event.click.load="Products">
                        <span
                            class="uk-margin-small-right"
                            uk-icon="icon: list"/>
                        <span> Libraries</span>
                    </a>
                </li>
                <li>
                    <a
                        href="#Products/updateProducts"
                        core.event.click.load="Products/updateProducts">
                        <span
                            class="uk-margin-small-right"
                            uk-icon="icon: code"/>
                        <span> Javascript</span>
                    </a>
                </li>
                <li>
                    <a
                        href="#Backups/archiveCatalogue"
                        core.event.click.load="Backups/archiveCatalogue">
                        <span
                            class="uk-margin-small-right"
                            uk-icon="icon: hashtag"/>
                        <span> CSS, SCSS, LESS</span>
                    </a>
                </li>
                <li>
                    <a
                        href="#Export/products"
                        core.event.click.load="Export/products">
                        <span
                            class="uk-margin-small-right"
                            uk-icon="icon: uikit"/>
                        <span> Fonts & Icon Sets</span>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</div>
