<div
    class="nav-main-aside right uk-navbar-nav uk-thumbnav-vertical">
    <ul class="uk-navbar-nav uk-thumbnav-vertical">
        <li class="uk-text-center">
            <a
                style="height: 110px"
                href="#Databases"
                core.event.click.load="Databases/index">
                <i uk-icon="icon: database"/>
                <span> Databases</span>
            </a>
        </li>
        <li class="uk-text-center">
            <a
                style="height: 80px"
                href="#Notes"
                core.event.click.load="Notes/index">
                <i uk-icon="icon: file-edit"/>
                <span> Notes</span>
            </a>
        </li>
        <li class="uk-text-center">
            <a
                style="height: 70px"
                href="#Tasks"
                core.event.click.load="Tasks/index">
                <i uk-icon="icon: check"/>
                <span> Tasks</span>
            </a>
        </li>
        <li class="uk-text-center">
            <a
                style="height: 135px"
                href="#Logs/timeTracking"
                core.event.click.load="Logs/timeTracking">
                <i uk-icon="icon: clock"/>
                <span> Time&amp;nbsp;Tracking</span>
            </a>
        </li>
    </ul>
</div>