<ul class="uk-breadcrumb uk-flex-auto uk-margin-remove">
    <li>
        <a
            href="#Admin"
            class="uk-active">
            <i uk-icon="icon: home; ratio: .75"></i>
            <span> CORE</span>
        </a>
    </li>
    <!--
    <li>
        <a href="#ProductDashboard">
            <i uk-icon="icon: bolt; ratio: .8"></i>
            <span> Dashboard</span>
        </a>
    </li>
    -->
</ul>
