<ul class="uk-navbar-nav uk-thumbnav-vertical">
    <li>
        <a href="http://www.fgx.co.za" target="_blank">
            <image
                width="45"
                src="/assets/images/fgx_logo_white.png"
                alt="Logo"/>
        </a>
    </li>

    <!--|| TOP LEFT NAV -->
    <div
        id="top-left-nav"
        class="main-left-nav-bar">

    </div>
    <!-- TOP LEFT NAV ||-->

    <!--|| BOTTOM LEFT NAV -->
    <div
        id="btm-left-nav"
        class="main-left-nav-bar"
        style="position: absolute; bottom: 10px">
        <li class="left-menu-item uk-text-center">
            <a
                class="left-menu-a"
                href="#Product/manageImages"
                uk-icon="icon: user"
                title="My Profile"
                uk-tooltip="true"
                core.event.click.load="User/myProfile">
            </a>
        </li>
        <li class="left-menu-item uk-text-center">
            <a
                class="left-menu-a"
                href="#User/signOut"
                uk-icon="icon: sign-out"
                title="Sign-Out"
                uk-tooltip="true"
                core.event.click.load="User/signOut">
            </a>
        </li>
    </div>
    <!-- BOTTOM LEFT NAV ||-->
</ul>
