<app.ws.top.tab
    icon="home"
    title="Welcome"
    active="yes"
    target="#cc-workspace .ws-left"/>

<div class="ws-left-credit" >
    <!-- Welcome Message -->
    <div class="core-heading">
        <small>PHP</small>
        <small> => </small>
        <small> HeEPP</small>
    </div>

    <!-- Code Name and Barcode -->
    <span class="core-sub-heading" class="font-fgx">
        <image src="/assets/images/HeEPP-fine-white.png" height="90"/>
    </span>
    <div>Hyper eXtensible Element PreProcessor</div>
</div>
<div class="welcome-statement">
    <h4>Some useful info</h4>
    <ul>
        <li>
            <small class="font-fgx">PHP </small>
            <b class="font-fgx"> 'HeEPP'</b>
            <span> is developed and maintained by </span>
            <a href="http://heepp.info" target="_blank" class="font-fgx">HeEPP Online</a>
        </li>
        <li>
            <span> Check out the </span>
            <a core.event.click.load="Wiki/index"
               href="#wiki/newFeatures">new features</a>
        </li>
        <li>
            <span>Download the printable </span>
            <a core.event.click.load="Wiki/index"
               href="#wiki/cheatsheet"> cheatsheet</a>
        </li>
        <li>
            <span>View the full </span>
            <a core.event.click.load="Wiki/index"
               href="#wiki/index">online documentation </a>
            <span>with code examples</span>
        </li>
    </ul>
</div>
