<ul
    id="left-section-nav"
    class="uk-nav-default uk-nav-parent-icon uk-padding-remove uk-nav">
    <li class="uk-nav-header margin-top-0">Console Settings</li>
    <li class="active">
        <a href="#">
            <span class="uk-margin-small-right fa fa-cogs fa-fw" />
            <span> Heepp Settings</span>
        </a>
    </li>
    <li>
        <a href="#">
            <span uk-icon="icon: world" class="uk-margin-small-right" />
            <span> Environment</span>
        </a>
    </li>
    <li>
        <a href="#">
            <span uk-icon="icon: code" class="uk-margin-small-right" />
            <span> Editor</span>
        </a>
    </li>
    <li>
        <a href="#">
            <span uk-icon="icon: gitter" class="uk-margin-small-right" />
            <span> Script Injection</span>
        </a>
    </li>
    <li>
        <a href="#">
            <span class="uk-margin-small-right fa fa-adjust fa-fw" />
            <span> Theme</span>
        </a>
    </li>
    <li>
        <a href="#">
            <span class="uk-margin-small-right fa fa-files-o fa-fw" />
            <span> View Config Files</span>
        </a>
    </li>
</ul>
