<!-- Container Tab -->
<app.ws.top.tab
    icon="question"
    title="HeEPP Wiki"
    active="false"
    target="#cc-workspace > section.ws-right"/>
<section class="cc-console-wiki">
    <!-- CORE Wiki Navigation -->
    <nav class="padding-left-30 padding-right-30 padding-top-15">
        <import src="views/wiki/intro.phtml"/>
        <import src="views/wiki/nav.phtml"/>
    </nav>

    <!-- Welcome Page -->
    <main>

    </main>
</section>
