<lazyload
    src="/views/projects/js/projects.js"
    instantiate="projects"
    extend="console"
    callback="core.console.projects.init"
    context="window"/>

<lazyload
    src="/views/projects/css/dashboard.scss"/>

<app.ws.top.tab
    icon="album"
    title="Projects | Dashboard"
    active="yes"
    target="#cc-workspace > section.ws-left"/>

<div id="projects-dashboard">
    <core.form
        id="projects-dashboard-date-filter-form"
        action="Project/Dashboard"
        method="post"
        class="dashboard-date-filters">
        <div class="uk-flex uk-flex-between">
            <div>
                <h4>Projects Dashboard</h4>
            </div>
            <div>
                <table>
                    <tr>
                        <td>
                            <small>From</small>
                        </td>
                        <td>
                            <uk.textfield
                                placeholder="From Date"
                                margin="none"
                                class="uk-form-small"
                                type="text"
                                value="${PREV_WEEK}"
                                icon="calendar"/>
                        </td>
                        <td>
                            <small>To</small>
                        </td>
                        <td>
                            <uk.textfield
                                placeholder="To Date"
                                margin="none"
                                class="uk-form-small"
                                type="text"
                                value="${CURRENT_DATE}"
                                icon="calendar"/>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </core.form>
    <div class="uk-container-expand">
        <div
            class="uk-grid uk-grid-divider uk-grid-medium uk-child-width-1-2 uk-child-width-1-4@l uk-child-width-1-5@xl"
            uk-grid="uk-grid">
            <div>
                <div class="uk-text-small">
                    <i
                        uk-icon="icon: users"
                        class="uk-margin-small-right uk-text-primary"/>
                    <span> New Projects</span>
                </div>
                <h1 class="uk-heading-primary uk-margin-remove uk-text-primary">5</h1>
                <div class="uk-text-small">
                    <i
                        uk-icon="icon: triangle-up"
                        class="uk-text-success"/>
                    <span>15% week on week.</span>
                </div>
            </div>
            <div>
                <div class="uk-text-small">
                    <i
                        uk-icon="icon:check"
                        class="uk-margin-small-right uk-text-primary"/>
                    <span> Project Tasks</span>
                </div>
                <h1 class="uk-heading-primary uk-margin-remove uk-text-primary">84</h1>
                <div class="uk-text-small">
                    <i
                        class="uk-text-warning"
                        uk-icon="icon: triangle-down"/>
                    <span> less week on week.</span>
                </div>
            </div>
            <div>
                <div class="uk-text-small">
                    <i
                        uk-icon="icon:clock"
                        class="uk-margin-small-right uk-text-primary"/>
                    <span> Time assigned to tasks</span>
                </div>
                <h1 class="uk-heading-primary uk-margin-remove uk-text-primary">
                    <span>106.00</span>
                    <small class="uk-text-small">Hours</small>
                </h1>
                <div class="uk-text-small">
                    <i
                        class="uk-text-success"
                        uk-icon="icon: triangle-up"/>
                    <span> 19% more week on week.</span>
                </div>
            </div>
            <div>
                <div class="uk-text-small">
                    <i
                        uk-icon="icon:pencil"
                        class="uk-margin-small-right uk-text-primary"/>
                    <span> Project &amp; Task Updates</span>
                </div>
                <h1 class="uk-heading-primary uk-margin-remove uk-text-primary">123</h1>
                <div class="uk-text-small">
                    <i
                        class="uk-text-danger"
                        uk-icon="icon: triangle-down"/>
                    <span> -23% less week on week.</span>
                </div>

            </div>
            <div class="uk-visible@xl">
                <div class="uk-text-small">
                    <i
                        uk-icon="icon:users"
                        class="uk-margin-small-right uk-text-primary"/>
                    <span> Lorem ipsum</span>
                </div>
                <h1 class="uk-heading-primary uk-margin-remove uk-text-primary">5.284</h1>
                <div class="uk-text-small">
                    <i
                        class="uk-text-success"
                        uk-icon="icon: triangle-up"/>
                    <span> 7% more week on week.</span>
                </div>
            </div>
        </div>
    </div>

    <div>
        <hr></hr>
    </div>

    <div
        class="uk-grid uk-grid-medium uk-grid-match"
        uk-grid="uk-grid">
        <div class="uk-width-1-2@s uk-width-1-3@l uk-width-1-4@xl">
            <div class="uk-card uk-card-secondary uk-card-small uk-card-hover">
                <div class="uk-card-header">
                    <div class="uk-grid uk-grid-small">
                        <div class="uk-width-auto">
                            <h4 class="uk-margin-remove-bottom">Recent Projects</h4>
                        </div>
                        <div class="uk-width-expand uk-text-right">
                            <a
                                href="#"
                                class="uk-icon-link uk-margin-small-right uk-icon"
                                uk-icon="icon: move">
                            </a>
                            <a
                                href="#"
                                class="uk-icon-link uk-margin-small-right uk-icon"
                                uk-icon="icon: cog">
                            </a>
                            <a
                                href="#"
                                class="uk-icon-link uk-icon"
                                uk-icon="icon: close">
                            </a>
                        </div>
                    </div>
                </div>
                <div class="uk-card-body">
                    <img src="img/mapa2.svg" alt=""/>
                    <p class="uk-text-muted uk-text-small uk-text-center">
                        Click on the projects above to view related tasks
                    </p>
                </div>
            </div>
        </div>

        <div class="uk-width-2-3@l uk-width-1-2@xl uk-first-column">
            <div class="uk-card uk-card-primary uk-card-small uk-card-hover">
                <div class="uk-card-header">
                    <div class="uk-grid uk-grid-small">
                        <div class="uk-width-auto">
                            <h4 class="uk-margin-remove-bottom">
                                Quick Tasks &amp; Time Logging
                            </h4>
                        </div>
                        <div class="uk-width-expand uk-text-right">
                            <a
                                href="#"
                                class="uk-icon-link uk-margin-small-right uk-icon"
                                uk-icon="icon: move">
                            </a>
                            <a
                                href="#"
                                class="uk-icon-link uk-margin-small-right uk-icon"
                                uk-icon="icon: cog">
                            </a>
                            <a
                                href="#"
                                class="uk-icon-link uk-icon"
                                uk-icon="icon: close">
                            </a>
                        </div>
                    </div>
                </div>
                <div class="uk-card-body">
                    <img src="img/mapa1.svg" alt=""/>
                    <p class="uk-text-muted uk-text-small uk-text-center">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <h4>
        Version Control
    </h4>
    <div>
        <hr></hr>
    </div>


    <div
        class="uk-grid uk-grid-medium uk-grid-match"
        uk-grid="uk-grid">
        <div class="uk-width-1-2@s uk-width-1-2@l uk-width-1-4@xl uk-grid-margin uk-first-column">
            <div class="uk-card uk-card-secondary uk-card-small uk-card-hover">
                <div class="uk-card-header">
                    <div class="uk-grid uk-grid-small">
                        <div class="uk-width-auto">
                            <h4 class="uk-margin-remove-bottom">Commit Project Assets</h4>
                        </div>
                        <div class="uk-width-expand uk-text-right">
                            <a
                                href="#"
                                class="uk-icon-link uk-margin-small-right uk-icon"
                                uk-icon="icon: move"></a>
                            <a
                                href="#"
                                class="uk-icon-link uk-margin-small-right uk-icon"
                                uk-icon="icon: cog"></a>
                            <a
                                href="#"
                                class="uk-icon-link uk-icon"
                                uk-icon="icon: close"></a>
                        </div>
                    </div>
                </div>
                <div class="uk-card-body">
                    <img src="img/mapa4.svg" alt=""/>
                    <p class="uk-text-muted uk-text-small uk-text-center">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    </p>
                </div>
            </div>
        </div>

        <div class="uk-width-1-2@s uk-width-1-2@l uk-width-1-4@xl uk-grid-margin">
            <div class="uk-card uk-card-secondary uk-card-small uk-card-hover">
                <div class="uk-card-header">
                    <div class="uk-grid uk-grid-small">
                        <div class="uk-width-auto">
                            <h4 class="uk-margin-remove-bottom">Pull Project Changes</h4>
                        </div>
                        <div class="uk-width-expand uk-text-right">
                            <a
                                href="#"
                                class="uk-icon-link uk-margin-small-right uk-icon"
                                uk-icon="icon: move">
                            </a>
                            <a
                                href="#"
                                class="uk-icon-link uk-margin-small-right uk-icon"
                                uk-icon="icon: cog">
                            </a>
                            <a
                                href="#"
                                class="uk-icon-link uk-icon"
                                uk-icon="icon: close">
                            </a>
                        </div>
                    </div>
                </div>
                <div class="uk-card-body">
                    <img src="img/mapa4.svg" alt=""/>
                    <p class="uk-text-muted uk-text-small uk-text-center">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
