<div
    id="top-nav"
    class="section header uk-padding-remove">
    <nav
        class="file-style-nav uk-navbar-container uk-padding-remove uk-background-secondary uk-light"
        uk-navbar="mode: click">
        <div class="uk-navbar-left uk-padding-remove uk-background-secondary">
            <ul class="uk-navbar-nav uk-background-secondary">
                <li>
                    <a href="#">
                        <u>F</u><span>ile</span>
                    </a>
                    <div class="uk-navbar-dropdown">
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            <li class="uk-active">
                                <a href="#">
                                    <i uk-icon="icon: folder"/>
                                    <span class="uk-margin-small-left"> Projects...</span>
                                </a>
                            </li>
                            <li class="uk-box-shadow-hover-small">
                                <a href="#" class="uk-box-shadow-hover-medium">
                                    <i uk-icon="icon: plus"/>
                                    <span class="uk-margin-small-left"> New</span>
                                </a>
                            </li>
                            <li class="uk-box-shadow-hover-small">
                                <a href="#">
                                    <i uk-icon="icon: file-edit"/>
                                    <span class="uk-margin-small-left"> Open File</span>
                                </a>
                            </li>
                            <li class="uk-box-shadow-hover-small">
                                <a href="#">
                                    <i uk-icon="icon: folder"/>
                                    <span class="uk-margin-small-left"> Open Directory</span>
                                </a>
                            </li>
                            <li class="uk-box-shadow-hover-small">
                                <a href="#">
                                    <i uk-icon="icon: link"/>
                                    <span class="uk-margin-small-left"> Open URL...</span>
                                </a>
                            </li>
                            <li class="uk-box-shadow-hover-small">
                                <a href="#">
                                    <i class="fa fa-save fa-fw"/>
                                    <span class="uk-margin-small-left"> Save As...</span>
                                </a>
                            </li>
                            <li class="uk-nav-divider"></li>
                            <li class="uk-box-shadow-hover-small">
                                <a href="#">
                                    <i uk-icon="icon: code"/>
                                    <span class="uk-margin-small-left"> Export HTML</span>
                                </a>
                            </li>
                            <li class="uk-box-shadow-hover-small">
                                <a href="#">
                                    <i class="fa fa-adjust"/>
                                    <span class="uk-margin-small-left"> Export CSS</span>
                                </a>
                            </li>
                            <li class="uk-box-shadow-hover-small">
                                <a href="#">
                                    <i class="fa fa-file-code-o fa-fw"/>
                                    <span class="uk-margin-small-left"> Export JS</span>
                                </a>
                            </li>
                            <li class="uk-box-shadow-hover-small">
                                <a href="#">
                                    <i class="fa fa-file-text-o fa-fw"/>
                                    <span class="uk-margin-small-left"> Data and JSON</span>
                                </a>
                            </li>
                            <li class="uk-box-shadow-hover-small">
                                <a href="#">
                                    <i class="fa fa-eye"/>
                                    <span class="uk-margin-small-left"> Show My Session ID</span>
                                </a>
                            </li>
                            <li class="uk-nav-divider"></li>
                            <li class="uk-box-shadow-hover-small">
                                <a href="#">
                                    <i uk-icon="icon: close"/>
                                    <span class="uk-margin-small-left"> Close Project</span>
                                </a>
                            </li>
                            <li class="uk-box-shadow-hover-small">
                                <a href="#">
                                    <i uk-icon="icon: lock"/>
                                    <span class="uk-margin-small-left"> Lock Screen</span>
                                </a>
                            </li>
                            <li class="uk-box-shadow-hover-small">
                                <a href="#">
                                    <i uk-icon="icon: sign-out"/>
                                    <span class="uk-margin-small-left"> Exit Console</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="#">Edit</a>
                    <div class="uk-navbar-dropdown">
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            <li class="uk-active"><a href="#">Active</a></li>
                            <li><a href="#">Item</a></li>
                            <li><a href="#">Item</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="#">View</a>
                    <div class="uk-navbar-dropdown">
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            <li class="uk-active"><a href="#">Active</a></li>
                            <li><a href="#">Item</a></li>
                            <li><a href="#">Item</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="#">Run</a>
                    <div class="uk-navbar-dropdown">
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            <li class="uk-active"><a href="#">Active</a></li>
                            <li><a href="#">Item</a></li>
                            <li><a href="#">Item</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="#">Source</a>
                    <div class="uk-navbar-dropdown">
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            <li class="uk-active"><a href="#">Active</a></li>
                            <li><a href="#">Item</a></li>
                            <li><a href="#">Item</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="#">VCS</a>
                    <div class="uk-navbar-dropdown">
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            <li class="uk-active"><a href="#">Active</a></li>
                            <li><a href="#">Item</a></li>
                            <li><a href="#">Item</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="#">Help</a>
                    <div class="uk-navbar-dropdown">
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            <li class="uk-active"><a href="#">Active</a></li>
                            <li><a href="#">Item</a></li>
                            <li><a href="#">Item</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="#">Item</a>
                </li>
                <div class="top-nav-info-btn">
                    <a href="#inspect" id="inspection-panel-icon" uk-tooltip="title: Inspection Panel">
                        <i uk-icon="icon: info"/>
                    </a>
                </div>
            </ul>
        </div>
    </nav>
    <div
        id="dev-top-sub-nav"
        class="top-sub-nav uk-flex uk-flex-left"
        uk-grid="uk-grid">
        <div class="breadcrumb-panel uk-section uk-padding-remove uk-section-default">
            <ul class="uk-breadcrumb uk-flex-auto">
                <li>

                    <a href="#Admin" class="uk-active">
                        <i uk-icon="icon: bolt; ratio: 1"></i>
                        <span> CORE</span>
                    </a>
                </li>
                <li>
                    <a href="#ProductDashboard" class="uk-active">
                        <i uk-icon="icon: nut; ratio: .8"></i>
                        <span> ${env.project.name}</span>
                    </a>
                </li>
            </ul>
        </div>
        <div id="top-icon-nav-left" class="top-icon-nav uk-flex-1">
            <ul class="uk-iconnav">
                <li>
                    <uk.textfield
                        class="uk-form-small top-nav-search"
                        placeholder="Search"
                        icon="search"/>
                </li>
                <li><a href="#" uk-icon="icon: social" uk-tooltip="title: Share"></a></li>
                <li><a href="#" uk-icon="icon: git-branch" uk-tooltip="title: GIT: Branch"></a></li>
                <li><a href="#" uk-icon="icon: git-fork" uk-tooltip="title: GIT: Fork"></a></li>
                <li><a href="#" uk-icon="icon: plus" uk-tooltip="title: GIT: Commit"></a></li>
                <li><a href="#" uk-icon="icon: pull" uk-tooltip="title: GIT: Pull"></a></li>
                <li><a href="#" uk-icon="icon: push" uk-tooltip="title: GIT: Push"></a></li>
                <li><a href="#" uk-icon="icon: server" uk-tooltip="title: Server Status"></a></li>
                <li><a href="#" uk-icon="icon: database" uk-tooltip="title: Database Management"></a></li>
            </ul>
        </div>
        <div id="top-icon-nav-right" class="top-icon-nav top-icon-nav-right uk-flex-1">
            <ul class="uk-iconnav">
                <li><a href="#" uk-icon="icon: refresh" uk-tooltip="title: Refresh"></a></li>
                <li><a href="#" uk-icon="icon: question" uk-tooltip="title: Request Help"></a></li>
                <li><a href="#" uk-icon="icon: commenting" uk-tooltip="title: Chat"></a></li>
                <li><a href="#" uk-icon="icon: bell" uk-tooltip="title: Tasks"></a></li>
            </ul>
        </div>
    </div>
</div>
