<lazyload
    path="${env.core.element.path}files/fileTree/js/"
    url="${env.core.element.url}files/fileTree/js/"
    file="fileTree.js"
    src="${env.core.element.url}files/fileTree/js/fileTree.js"/>
<lazyload
    path="${env.core.element.path}files/fileTree/css/"
    url="${env.core.element.url}files/fileTree/css/"
    file="fileTree.scss"/>
<lazyload
    src="${env.core.element.url}files/fileTree/css/icons/flaticon.css"/>
<div id="element-file-tree">
    @{tree}
</div>